name: just_movie_it
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.1.0
  go_router: ^6.0.7
  http: ^0.13.5
  mocktail: ^0.3.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
